version: '3.8'

name: bankapi

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DB}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DATASOURCE_DB}
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: